In [3]:
X,y = zip(['a',1], ['b',2], ['c',3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [4]:
sequences = [['a',1],['b',2],['c',3]]
X,y = zip(*sequences)
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [19]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!',1],
         ['내일 뵐 수 있을지 확인 부탁드...',0],
         ['도연씨, 잘지내고 계시죠? 오랜만입...',0],
         ['(광고) AI로 주가를 예측할 수 있다!',1]]
columns = ['메일 본문','스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2  도연씨, 잘지내고 계시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [20]:
X=df['메일 본문']
y=df['스팸 메일 유무']

In [15]:
print(X)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2    도연씨, 잘지내고 계시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object


In [21]:
print(y)

0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


In [22]:
import numpy as np
ar = np.arange(0,16).reshape(4,4)
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
X = ar[:,:3]
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [24]:
y=ar[:,3]
print(y)

[ 3  7 11 15]


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

In [26]:
X, y = np.arange(10).reshape((5,2)), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.33, random_state=1234)

In [28]:
print(X_train)
print(X_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]


In [29]:
print(y_train)
print(y_test)

[1, 2, 3]
[4, 0]


In [32]:
X, y = np.arange(0,24).reshape((12,2)), range(12)
print(X)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [33]:
print(list(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [34]:
n_of_train = int(len(X) * 0.8)
n_of_test = int(len(X) - n_of_train) #len(X)*0.2는 데이터 누락이 발생할수도있으므로 빼주어야 한다
print(n_of_train)
print(n_of_test)

9
3


In [35]:
X_test = X[n_of_train:]#데이터 중에서 뒤의 20%만큼 저장
y_test = y[n_of_train:]
X_train = X[:n_of_train]#데이터 중에서 앞의 80%만큼 저장
y_train = y[:n_of_train]

In [36]:
print(X_test)
print(list(y_test))

[[18 19]
 [20 21]
 [22 23]]
[9, 10, 11]


In [37]:
#정수 인코딩

In [73]:
text = "A barber is a person. a barber is a good person. a barber is a huge person. he knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [74]:
from nltk.tokenize import sent_tokenize
text = sent_tokenize(text)

In [75]:
print(text)

['A barber is a person.', 'a barber is a good person.', 'a barber is a huge person.', 'he knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [76]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter
vocab = Counter() #단어 빈도 세기 좋은 모듈

sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i)#단어의 토큰화 수행
    result = []
    
    for word in sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2:
                result.append(word)
                vocab[word] = vocab[word] + 1
    sentences.append(result)
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [47]:
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [48]:
vocab_sorted = sorted(vocab.items(), key=lambda x:x[1], reverse=True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [50]:
word_to_index = {}
i = 0
for (word, frequency) in vocab_sorted:
    if frequency > 1:
        i += 1
        word_to_index[word] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [51]:
from keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts(text)

In [52]:
print(t.word_index)

{'a': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'his': 5, 'is': 6, 'kept': 7, 'person': 8, 'the': 9, 'he': 10, 'word': 11, 'keeping': 12, 'good': 13, 'knew': 14, 'but': 15, 'and': 16, 'such': 17, 'to': 18, 'himself': 19, 'was': 20, 'driving': 21, 'crazy': 22, 'went': 23, 'up': 24, 'mountain': 25}


In [53]:
print(t.word_counts)

OrderedDict([('a', 10), ('barber', 8), ('is', 4), ('person', 3), ('good', 1), ('huge', 5), ('he', 2), ('knew', 1), ('secret', 6), ('the', 3), ('kept', 4), ('his', 5), ('word', 2), ('but', 1), ('keeping', 2), ('and', 1), ('such', 1), ('to', 1), ('himself', 1), ('was', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('up', 1), ('mountain', 1)])


In [54]:
print(t.texts_to_sequences(text))

[[1, 2, 6, 1, 8], [1, 2, 6, 1, 13, 8], [1, 2, 6, 1, 4, 8], [10, 14, 1, 3], [9, 3, 10, 7, 6, 4, 3], [4, 3], [5, 2, 7, 5, 11], [1, 2, 7, 5, 11], [5, 2, 7, 5, 3], [15, 12, 16, 12, 17, 1, 4, 3, 18, 19, 20, 21, 9, 2, 22], [9, 2, 23, 24, 1, 4, 25]]


In [55]:
words_frequency = [w for w,c in t.word_counts.items() if c < 2] #빈도수 2 미만인 단어를 w 라고 저장
for w in words_frequency:
    del t.word_index[w] #해당 단어에 대한 인덱스 정볼ㄹ 삭제
    del t.word_counts[w] #해당 단어에 대한 카운트 정보를 삭제
print(t.texts_to_sequences(text))
print(t.word_index)

[[1, 2, 6, 1, 8], [1, 2, 6, 1, 8], [1, 2, 6, 1, 4, 8], [10, 1, 3], [9, 3, 10, 7, 6, 4, 3], [4, 3], [5, 2, 7, 5, 11], [1, 2, 7, 5, 11], [5, 2, 7, 5, 3], [12, 12, 1, 4, 3, 9, 2], [9, 2, 1, 4]]
{'a': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'his': 5, 'is': 6, 'kept': 7, 'person': 8, 'the': 9, 'he': 10, 'word': 11, 'keeping': 12}


In [57]:
test = [8,2,5,1,3,7,9,4,6,10]

for index, value in enumerate(test):
    print("index : {}, value : {}".format(index,value))

index : 0, value : 8
index : 1, value : 2
index : 2, value : 5
index : 3, value : 1
index : 4, value : 3
index : 5, value : 7
index : 6, value : 9
index : 7, value : 4
index : 8, value : 6
index : 9, value : 10


In [91]:
text = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [95]:
vocab = sum(text, [])
print(vocab)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [96]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter
vocab = Counter()
stop_words = set(stopwords.words('english'))

for word in sentence:
    word = word.lower()
    if word not in stop_words:
        vocab[word] = vocab[word] +1
print(vocab)

Counter({'barber': 1, 'went': 1, 'huge': 1, 'mountain': 1, '.': 1})
